    <link rel="stylesheet" href="client/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <link rel="stylesheet" href="client/plugins/OwlCarousel2/css/owl.carousel.min.css">
    <link rel="stylesheet" href="client/plugins/OwlCarousel2/css/owl.theme.default.css">
    <link rel="stylesheet" href="client/css/style.css">
    <link rel="stylesheet" href="client/css/index.css">
    <link rel="stylesheet" href="client/css/animate.css">
    <link rel="stylesheet" href="client/css/order.css">
    <link rel="stylesheet" href="client/css/lightslider.css">
    <link rel="stylesheet" href="client/css/detail-p.css">
    <link rel="icon" href="client/images/icon.png">