    <link rel="stylesheet" href="{{asset('client/plugins/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <link rel="stylesheet" href="{{asset('client/plugins/OwlCarousel2/css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{asset('client/plugins/OwlCarousel2/css/owl.theme.default.css')}}">
    <link rel="stylesheet" href="{{asset('client/css/style.css')}}">
    <link rel="stylesheet" href="{{asset('client/css/index.css')}}">
    <link rel="stylesheet" href="{{asset('client/css/animate.css')}}">
    <link rel="stylesheet" href="{{asset('client/css/compare.css')}}">
    <link rel="stylesheet" href="{{asset('client/css/order.css')}}">
    <link rel="stylesheet" href="{{asset('client/css/lightslider.css')}}">
    <link rel="stylesheet" href="{{asset('client/css/detail-p.css')}}">
    <link rel="icon" href="{{asset('client/images/icon.png')}}">
